version: '3'
services:
  db2:
    image: postgres:latest
    container_name: db2
    environment:
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"

  alten-hotel-service:
    build: .
    container_name: alten-hotel-service
    ports:
      - "8081:8081"
    environment:
      - DB1_URL=jdbc:postgresql://db2:5432/postgres
    links:
      - db2
    depends_on:
      - db2
    restart: unless-stopped