version: '3'
services:
  db1:
    image: postgres:latest
    container_name: db1
    environment:
      - POSTGRES_PASSWORD=test
    ports:
      - "5432"

  alten-hotel-service:
    build: .
    container_name: alten-hotel-service
    ports:
      - "8081:8081"
    environment:
      - DB1_URL=jdbc:postgresql://db1:5432/postgres
    links:
      - db1
    depends_on:
      - db1
    restart: unless-stopped